name: theme
description: Theme state management (mode + color scheme) for the Flutter starter template.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.3.0
  analytics: ^0.1.0
  architecture: ^0.1.0
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1
  injectable: ^3.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner: ^2.15.1
  injectable_generator: ^3.0.2
  test_utils: ^0.1.0
