import 'package:feature_bookmarks/feature_bookmarks.dart';
import 'package:feature_collections/feature_collections.dart';
import 'package:feature_notifications/feature_notifications.dart';
import 'package:go_router/go_router.dart';

import 'di/injection.dart';
import 'feature_module.dart';

/// All optional features enabled in this project.
///
/// Generated by `fst create` — edit to add or remove features.
const List<FeatureModule> enabledFeatures = [
  _BookmarksModule(),
  _CollectionsModule(),
  _NotificationsModule(),
  // fst:enabled-features — `fst add-feature` inserts new modules above this line
];

final class _BookmarksModule extends FeatureModule {
  const _BookmarksModule();

  @override
  FeatureSyncController get syncController {
    final ctrl = getIt<BookmarksSyncController>();
    return _FeatureSync(onStart: ctrl.start, onStop: ctrl.stop);
  }

  @override
  Iterable<RouteBase> get routes => bookmarksRoutes;
}

final class _CollectionsModule extends FeatureModule {
  const _CollectionsModule();

  @override
  FeatureSyncController get syncController {
    final ctrl = getIt<CollectionsSyncController>();
    return _FeatureSync(onStart: ctrl.start, onStop: ctrl.stop);
  }

  @override
  Iterable<RouteBase> get routes => collectionsRoutes;
}

final class _NotificationsModule extends FeatureModule {
  const _NotificationsModule();

  @override
  FeatureSyncController get syncController {
    final ctrl = getIt<NotificationsSyncController>();
    return _FeatureSync(onStart: ctrl.start, onStop: ctrl.stop);
  }
}

// fst:feature-module-classes — `fst add-feature` inserts new module classes above

/// Adapts any feature's sync controller to [FeatureSyncController] without a
/// bespoke wrapper class per feature. The controllers don't implement the
/// interface directly so feature packages stay unaware of the app's lifecycle.
final class _FeatureSync implements FeatureSyncController {
  const _FeatureSync({required this.onStart, required this.onStop});

  final Future<void> Function() onStart;
  final Future<void> Function() onStop;

  @override
  Future<void> start() => onStart();

  @override
  Future<void> stop() => onStop();
}
