import 'package:feature_bookmarks/feature_bookmarks.dart';
import 'package:feature_collections/feature_collections.dart';
import 'package:feature_notifications/feature_notifications.dart';

import 'di/injection.dart';
import 'feature_module.dart';

/// All optional features enabled in this project.
///
/// Generated by `fst create` — edit to add or remove features.
const List<FeatureModule> enabledFeatures = [
  _BookmarksModule(),
  _CollectionsModule(),
  _NotificationsModule(),
];

final class _BookmarksModule extends FeatureModule {
  const _BookmarksModule();

  @override
  FeatureSyncController get syncController =>
      _BookmarksSync(getIt<BookmarksSyncController>());
}

final class _CollectionsModule extends FeatureModule {
  const _CollectionsModule();

  @override
  FeatureSyncController get syncController =>
      _CollectionsSync(getIt<CollectionsSyncController>());
}

final class _NotificationsModule extends FeatureModule {
  const _NotificationsModule();

  @override
  FeatureSyncController get syncController =>
      _NotificationsSync(getIt<NotificationsSyncController>());
}

final class _BookmarksSync implements FeatureSyncController {
  const _BookmarksSync(this._ctrl);
  final BookmarksSyncController _ctrl;
  @override
  Future<void> start() => _ctrl.start();
  @override
  Future<void> stop() => _ctrl.stop();
}

final class _CollectionsSync implements FeatureSyncController {
  const _CollectionsSync(this._ctrl);
  final CollectionsSyncController _ctrl;
  @override
  Future<void> start() => _ctrl.start();
  @override
  Future<void> stop() => _ctrl.stop();
}

final class _NotificationsSync implements FeatureSyncController {
  const _NotificationsSync(this._ctrl);
  final NotificationsSyncController _ctrl;
  @override
  Future<void> start() => _ctrl.start();
  @override
  Future<void> stop() => _ctrl.stop();
}
